#include "config.h"

#include "cli.hpp"
#include "config.hpp"
#include "makefs.hpp"
#include "util.hpp"

#include <cctype>
#include <cstdio>
#include <cstring>
#include <dirent.h>
#include <fstream>
#include <sstream>
#include <sys/stat.h>

static const Subcommand subcommands[]
    = { { "search", N_ ("<keyword>"),
          N_ ("Search available packages"),
          cmd_search },
        { "install", N_ ("<packages...>"),
          N_ ("Install packages and dependencies"),
          cmd_install },
        { "remove", N_ ("<packages...>"),
          N_ ("Remove installed packages"),
          cmd_remove },
        { "rebuild", N_ ("[packages...]"),
          N_ ("Rebuild installed packages"),
          cmd_rebuild },
        { "list", "",
          N_ ("List installed packages"),
          cmd_list },
        { "update", "",
          N_ ("Update package metadata from remote"),
          cmd_update },
        { "register", N_ ("<pkg> [version] [deps...]"),
          N_ ("Register manually-installed package"),
          cmd_register },
        { "unregister", N_ ("<pkg>"),
          N_ ("Unregister a manual package"),
          cmd_unregister },
        { nullptr, nullptr, nullptr, nullptr } };

void
print_usage (const char* prog)
{
  std::printf (_ ("Usage: %s <command> [options...]\n\n"), prog);
  std::printf ("%s\n\n", _ ("Commands:"));

  for (const Subcommand* sc = subcommands; sc->name != nullptr; ++sc)
    {
      if (sc->args[0] != '\0')
        std::printf ("  %-12s %-22s %s\n", sc->name, sc->args,
                     _ (sc->desc));
      else
        std::printf ("  %-12s %-22s %s\n", sc->name, "", _ (sc->desc));
    }

  std::printf ("\n%s\n", _ ("Options:"));
  std::printf ("  %-12s %-22s %s\n", "--help", "", _ ("Show this help"));
  std::printf ("  %-12s %-22s %s\n", "--version", "",
               _ ("Show version information"));
}

void
print_version ()
{
  std::printf ("qp %s\n", PACKAGE_VERSION);
  std::printf ("%s\n",
               _ ("Copyright (C) 2026 Qaaxaap.  License GPLv3+."));
}

static int
not_impl (const char* name)
{
  std::printf (_ ("%s: not yet implemented.\n"), name);
  return 0;
}

/* ------------------------------------------------------------------ */

static int
generate_index (const std::string &repo_dir, std::string &err)
{
  std::string pkg_dir = repo_dir + "/packages";
  std::string meta_dir = repo_dir + "/meta";

  run_command ({ "mkdir", "-p", meta_dir });

  std::string index_path = meta_dir + "/index";
  std::ofstream out (index_path);
  if (!out)
    {
      err = "cannot write " + index_path;
      return -1;
    }

  out << "# qur package index — generated by qp update\n";
  out << "# TAB separated: SOURCE\tNAME\tVERSION\tDESCRIPTION\n";

  int count = 0;

  DIR *dir = opendir (pkg_dir.c_str ());
  if (dir == nullptr)
    return 0;

  struct dirent *ent;
  while ((ent = readdir (dir)) != nullptr)
    {
      if (ent->d_name[0] == '.')
        continue;

      std::string makefs_path
          = pkg_dir + "/" + ent->d_name + "/MAKEFS";

      struct stat st;
      if (stat (makefs_path.c_str (), &st) != 0)
        continue;

      qp::MakefsSpec spec;
      std::string parse_err;
      if (!qp::parse_makefs (makefs_path, spec, parse_err))
        continue;

      /* Main package. */
      out << spec.name << "\t" << spec.name << "\t" << spec.version
          << "\t" << spec.description << "\n";
      ++count;

      /* Sub-packages. */
      for (const auto &sub : spec.subpackages)
        {
          out << spec.name << "\t" << sub.name << "\t"
              << spec.version << "\t" << sub.description << "\n";
          ++count;
        }
    }
  closedir (dir);
  return count;
}

/* ------------------------------------------------------------------ */

int
cmd_update (int argc, char **argv)
{
  (void)argc;
  (void)argv;

  Config cfg = load_config ();

  /* Create parent directory. */
  size_t slash = cfg.repo_dir.rfind ('/');
  if (slash != std::string::npos)
    run_command ({ "mkdir", "-p", cfg.repo_dir.substr (0, slash) });

  struct stat st;
  if (stat (cfg.repo_dir.c_str (), &st) != 0)
    {
      std::printf (_ ("Cloning %s...\n"), cfg.repo_url.c_str ());
      int rc = run_command (
          { "git", "clone", cfg.repo_url, cfg.repo_dir });
      if (rc != 0)
        {
          std::printf (_ ("error: git clone failed\n"));
          return 1;
        }
    }
  else
    {
      std::string dotgit = cfg.repo_dir + "/.git";
      if (stat (dotgit.c_str (), &st) == 0)
        {
          std::printf (_ ("Updating %s...\n"), cfg.repo_dir.c_str ());
          int rc = run_command (
              { "git", "-C", cfg.repo_dir, "pull", "--ff-only" });
          if (rc != 0)
            {
              std::printf (_ ("error: git pull failed\n"));
              return 1;
            }
        }
    }

  std::string err;
  int count = generate_index (cfg.repo_dir, err);
  if (count < 0)
    {
      std::printf ("%s\n", err.c_str ());
      return 1;
    }

  std::printf (_ ("Indexed %d package(s).\n"), count);
  return 0;
}

int
cmd_search (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp search <keyword>\n"));
      return 1;
    }

  Config cfg = load_config ();
  std::string keyword = argv[1];

  std::ifstream in (cfg.repo_dir + "/meta/index");
  if (!in)
    {
      std::printf (
          _ ("No package index found. Run 'qp update' first.\n"));
      return 1;
    }

  bool found = false;
  std::string line;
  while (std::getline (in, line))
    {
      if (line.empty () || line[0] == '#')
        continue;

      std::vector<std::string> fields;
      std::istringstream ss (line);
      std::string field;
      while (std::getline (ss, field, '\t'))
        fields.push_back (field);

      if (fields.size () < 4)
        continue;

      std::string name_low = fields[1];
      std::string desc_low = fields[3];
      for (auto &c : name_low)
        c = static_cast<char> (std::tolower (
            static_cast<unsigned char> (c)));
      for (auto &c : desc_low)
        c = static_cast<char> (std::tolower (
            static_cast<unsigned char> (c)));

      std::string kw_low = keyword;
      for (auto &c : kw_low)
        c = static_cast<char> (std::tolower (
            static_cast<unsigned char> (c)));

      if (name_low.find (kw_low) != std::string::npos
          || desc_low.find (kw_low) != std::string::npos)
        {
          found = true;
          if (fields[0] == fields[1])
            std::printf ("%-28s %-10s %s\n", fields[1].c_str (),
                         fields[2].c_str (), fields[3].c_str ());
          else
            std::printf ("%-28s %-10s %s (%s %s)\n",
                         fields[1].c_str (), fields[2].c_str (),
                         fields[3].c_str (), _ ("from"),
                         fields[0].c_str ());
        }
    }

  if (!found)
    std::printf (
        _ ("No packages found matching '%s'.\n"), keyword.c_str ());

  return 0;
}

int
cmd_install (int, char**) { return not_impl ("install"); }
int
cmd_remove (int, char**) { return not_impl ("remove"); }
int
cmd_rebuild (int, char**) { return not_impl ("rebuild"); }
int
cmd_list (int, char**) { return not_impl ("list"); }
int
cmd_register (int, char**) { return not_impl ("register"); }
int
cmd_unregister (int, char**) { return not_impl ("unregister"); }

const Subcommand*
find_subcommand (const char* name)
{
  for (const Subcommand* sc = subcommands; sc->name != nullptr; ++sc)
    {
      if (std::strcmp (sc->name, name) == 0)
        return sc;
    }
  return nullptr;
}
