#include "config.h"

#include "cli.hpp"
#include "config.hpp"
#include "makefs.hpp"
#include "util.hpp"

#include <lfspkg/db.hpp>
#include <lfspkg/package.hpp>

#include <cctype>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <dirent.h>
#include <fstream>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

namespace fs = std::filesystem;

static const Subcommand subcommands[] = {
  { "search", N_ ("<keyword>"), N_ ("Search available packages"), cmd_search },
  { "install", N_ ("<packages...>"), N_ ("Install packages and dependencies"),
    cmd_install },
  { "remove", N_ ("<packages...>"), N_ ("Remove installed packages"),
    cmd_remove },
  { "rebuild", N_ ("[--stale|--all|<pkg>]"), N_ ("Rebuild installed packages"),
    cmd_rebuild },
  { "upgrade", N_ ("[packages...]"),
    N_ ("Upgrade installed packages to latest version"), cmd_upgrade },
  { "list", "", N_ ("List installed packages"), cmd_list },
  { "update", "", N_ ("Update package metadata from remote"), cmd_update },
  { "register", N_ ("<pkg> [version] [deps...]"),
    N_ ("Register manually-installed package"), cmd_register },
  { "unregister", N_ ("<pkg>"), N_ ("Unregister a manual package"),
    cmd_unregister },
  { nullptr, nullptr, nullptr, nullptr }
};

void
print_usage (const char *prog)
{
  std::printf (_ ("Usage: %s <command> [options...]\n\n"), prog);
  std::printf ("%s\n\n", _ ("Commands:"));

  for (const Subcommand *sc = subcommands; sc->name != nullptr; ++sc)
    {
      if (sc->args[0] != '\0')
        std::printf ("  %-12s %-22s %s\n", sc->name, sc->args, _ (sc->desc));
      else
        std::printf ("  %-12s %-22s %s\n", sc->name, "", _ (sc->desc));
    }

  std::printf ("\n%s\n", _ ("Options:"));
  std::printf ("  %-12s %-22s %s\n", "--help", "", _ ("Show this help"));
  std::printf ("  %-12s %-22s %s\n", "--version", "",
               _ ("Show version information"));
}

void
print_version ()
{
  std::printf ("qp %s\n", PACKAGE_VERSION);
  std::printf ("%s\n", _ ("Copyright (C) 2026 Qaaxaap.  License GPLv3+."));
}

/* ------------------------------------------------------------------ */

static int
generate_index (const std::string &repo_dir, std::string &err)
{
  std::string pkg_dir = repo_dir + "/packages";
  std::string meta_dir = repo_dir + "/meta";

  run_command ({ "mkdir", "-p", meta_dir });

  std::string index_path = meta_dir + "/index";
  std::ofstream out (index_path);
  if (!out)
    {
      err = "cannot write " + index_path;
      return -1;
    }

  out << "# qur package index — generated by qp update\n";
  out << "# TAB separated: SOURCE\tNAME\tVERSION\tDESCRIPTION\n";

  int count = 0;

  DIR *dir = opendir (pkg_dir.c_str ());
  if (dir == nullptr)
    return 0;

  struct dirent *ent;
  while ((ent = readdir (dir)) != nullptr)
    {
      if (ent->d_name[0] == '.')
        continue;

      std::string makefs_path = pkg_dir + "/" + ent->d_name + "/MAKEFS";

      struct stat st;
      if (stat (makefs_path.c_str (), &st) != 0)
        continue;

      qp::MakefsSpec spec;
      std::string parse_err;
      if (!qp::parse_makefs (makefs_path, spec, parse_err))
        continue;

      /* Main package. */
      out << spec.name << "\t" << spec.name << "\t" << spec.version << "\t"
          << spec.description << "\n";
      ++count;

      /* Sub-packages. */
      for (const auto &sub : spec.subpackages)
        {
          out << spec.name << "\t" << sub.name << "\t" << spec.version << "\t"
              << sub.description << "\n";
          ++count;
        }
    }
  closedir (dir);
  return count;
}

/* ------------------------------------------------------------------ */

int
cmd_update (int argc, char **argv)
{
  (void)argc;
  (void)argv;

  Config cfg = load_config ();

  /* Create parent directory. */
  size_t slash = cfg.repo_dir.rfind ('/');
  if (slash != std::string::npos)
    run_command ({ "mkdir", "-p", cfg.repo_dir.substr (0, slash) });

  struct stat st;
  if (stat (cfg.repo_dir.c_str (), &st) != 0)
    {
      std::printf (_ ("Cloning %s...\n"), cfg.repo_url.c_str ());
      int rc = run_command ({ "git", "clone", cfg.repo_url, cfg.repo_dir });
      if (rc != 0)
        {
          std::printf (_ ("error: git clone failed\n"));
          return 1;
        }
    }
  else
    {
      std::string dotgit = cfg.repo_dir + "/.git";
      if (stat (dotgit.c_str (), &st) == 0)
        {
          std::printf (_ ("Updating %s...\n"), cfg.repo_dir.c_str ());
          int rc = run_command (
              { "git", "-C", cfg.repo_dir, "pull", "--ff-only" });
          if (rc != 0)
            {
              std::printf (_ ("error: git pull failed\n"));
              return 1;
            }
        }
    }

  std::string err;
  int count = generate_index (cfg.repo_dir, err);
  if (count < 0)
    {
      std::printf ("%s\n", err.c_str ());
      return 1;
    }

  std::printf (_ ("Indexed %d package(s).\n"), count);
  return 0;
}

int
cmd_search (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp search <keyword>\n"));
      return 1;
    }

  Config cfg = load_config ();
  std::string keyword = argv[1];

  std::ifstream in (cfg.repo_dir + "/meta/index");
  if (!in)
    {
      std::printf (_ ("No package index found. Run 'qp update' first.\n"));
      return 1;
    }

  bool found = false;
  std::string line;
  while (std::getline (in, line))
    {
      if (line.empty () || line[0] == '#')
        continue;

      std::vector<std::string> fields;
      std::istringstream ss (line);
      std::string field;
      while (std::getline (ss, field, '\t'))
        fields.push_back (field);

      if (fields.size () < 4)
        continue;

      std::string name_low = fields[1];
      std::string desc_low = fields[3];
      for (auto &c : name_low)
        c = static_cast<char> (std::tolower (static_cast<unsigned char> (c)));
      for (auto &c : desc_low)
        c = static_cast<char> (std::tolower (static_cast<unsigned char> (c)));

      std::string kw_low = keyword;
      for (auto &c : kw_low)
        c = static_cast<char> (std::tolower (static_cast<unsigned char> (c)));

      if (name_low.find (kw_low) != std::string::npos
          || desc_low.find (kw_low) != std::string::npos)
        {
          found = true;
          if (fields[0] == fields[1])
            std::printf ("%-28s %-10s %s\n", fields[1].c_str (),
                         fields[2].c_str (), fields[3].c_str ());
          else
            std::printf ("%-28s %-10s %s (%s %s)\n", fields[1].c_str (),
                         fields[2].c_str (), fields[3].c_str (), _ ("from"),
                         fields[0].c_str ());
        }
    }

  if (!found)
    std::printf (_ ("No packages found matching '%s'.\n"), keyword.c_str ());

  return 0;
}

/* ------------------------------------------------------------------ */
/* install / rebuild helpers                                           */
/* ------------------------------------------------------------------ */

static lfspkg::PackageDB
make_db (const Config &cfg)
{
  (void)cfg;
  return lfspkg::PackageDB (lfspkg::default_db_root ());
}

/* Run a MAKEFS build: prepare, build, package.
   Returns the stage directory path. */
static std::string
run_makefs_build (const qp::MakefsSpec &spec, const Config &cfg)
{
  const std::string &name = spec.name;
  std::string stage = cfg.build_dir + "/stage/" + name;
  std::string build = cfg.build_dir + "/build/" + name;
  std::string srcdir = cfg.build_dir + "/source/" + name;

  /* Create build directories. */
  run_command ({ "mkdir", "-p", stage });
  run_command ({ "mkdir", "-p", build });
  run_command ({ "mkdir", "-p", srcdir });

  /* Build a wrapper script that defines MAKEFS variables and
     functions, then calls prepare + build + package. */
  std::string script_path = cfg.build_dir + "/_build_" + name + ".sh";
  std::ofstream script (script_path);
  if (!script)
    {
      std::printf (_ ("error: cannot write build script\n"));
      return "";
    }
  script << "#!/bin/bash\n";
  script << "set -e\n";
  script << "export STAGE='" << stage << "'\n";
  script << "export BUILD_DIR='" << build << "'\n";
  script << "export SRCDIR='" << srcdir << "'\n";
  script << "mkdir -p \"$STAGE\" \"$BUILD_DIR\" \"$SRCDIR\"\n";
  script << "cd \"$SRCDIR\"\n";

  /* Emit MAKEFS metadata as bash variables (no spaces around =). */
  script << "NAME='" << spec.name << "'\n";
  script << "VERSION='" << spec.version << "'\n";
  script << "RELEASE='" << spec.release << "'\n";

  /* Expand $(VAR) references in a string. */
  auto expand_vars = [&spec] (std::string body) -> std::string
    {
      auto subst = [&body] (const std::string &token, const std::string &value)
        {
          size_t pos = 0;
          while ((pos = body.find (token, pos)) != std::string::npos)
            {
              body.replace (pos, token.size (), value);
              pos += value.size ();
            }
        };
      subst ("$(NAME)", spec.name);
      subst ("$(VERSION)", spec.version);
      subst ("$(RELEASE)", spec.release);
      return body;
    };

  /* Emit functions as proper bash function definitions. */
  for (const auto &[fname, fbody] : spec.functions)
    {
      script << fname << "() {\n";
      script << expand_vars (fbody) << "\n";
      script << "}\n";
    }

  /* Pre-install hook. */
  if (!spec.pre_install.empty ())
    {
      script << spec.pre_install << "\n";
    }

  script << "cd \"$SRCDIR\" && prepare\n";
  script << "cd \"$SRCDIR\" && build\n";
  script << "cd \"$SRCDIR\" && package\n";
  script.close ();

  run_command ({ "chmod", "+x", script_path });

  std::printf (_ ("Building %s...\n"), name.c_str ());
  int rc = run_command ({ "bash", script_path });
  if (rc != 0)
    {
      std::printf (_ ("error: build failed for %s (exit %d)\n"), name.c_str (),
                   rc);
      return "";
    }

  return stage;
}

/* Install a single package: parse MAKEFS, build, register in db.
   The 'installing' set tracks the current call chain to detect cycles.
   Returns 0 on success. */
static int
install_package (const Config &cfg, lfspkg::PackageDB &db,
                 const std::string &name, std::set<std::string> &installing)
{
  if (db.installed (name))
    {
      std::printf (_ ("%s: already installed.\n"), name.c_str ());
      return 0;
    }

  std::string makefs_path = cfg.repo_dir + "/packages/" + name + "/MAKEFS";

  qp::MakefsSpec spec;
  std::string err;
  if (!qp::parse_makefs (makefs_path, spec, err))
    {
      std::printf (_ ("error: %s\n"), err.c_str ());
      return 1;
    }

  /* Mark this package as being installed (for cycle detection). */
  installing.insert (name);

  /* Install runtime dependencies first. */
  for (const auto &dep : spec.depends)
    {
      if (!db.installed (dep))
        {
          if (installing.count (dep))
            {
              std::printf (_ ("warning: cycle detected: %s <-> %s\n"),
                           name.c_str (), dep.c_str ());
              continue;
            }
          std::printf (_ ("Installing dependency: %s\n"), dep.c_str ());
          int rc = install_package (cfg, db, dep, installing);
          if (rc != 0)
            {
              installing.erase (name);
              return rc;
            }
        }
    }

  installing.erase (name);

  /* Build the package. */
  std::string stage = run_makefs_build (spec, cfg);
  if (stage.empty ())
    return 1;

  /* Register in lfspkg. */
  lfspkg::PackageSpec pkg_spec;
  pkg_spec.name = spec.name;
  pkg_spec.version = spec.version;
  pkg_spec.stage_dir = stage;
  pkg_spec.deps = spec.depends;

  try
    {
      lfspkg::apply_install_or_upgrade (db, pkg_spec, false);
    }
  catch (const std::exception &e)
    {
      std::printf ("%s: %s\n", _ ("install error"), e.what ());
      return 1;
    }

  std::printf (_ ("Installed %s %s\n"), spec.name.c_str (),
               spec.version.c_str ());
  return 0;
}

/* Rebuild a package (already installed). */
static int
rebuild_package (const Config &cfg, lfspkg::PackageDB &db,
                 const std::string &name)
{
  if (!db.installed (name))
    {
      std::printf (_ ("%s: not installed. Use 'qp install'.\n"),
                   name.c_str ());
      return 1;
    }

  std::string makefs_path = cfg.repo_dir + "/packages/" + name + "/MAKEFS";

  qp::MakefsSpec spec;
  std::string err;
  if (!qp::parse_makefs (makefs_path, spec, err))
    {
      std::printf (_ ("error: %s\n"), err.c_str ());
      return 1;
    }

  std::string stage = run_makefs_build (spec, cfg);
  if (stage.empty ())
    return 1;

  lfspkg::PackageSpec pkg_spec;
  pkg_spec.name = spec.name;
  pkg_spec.version = spec.version;
  pkg_spec.stage_dir = stage;
  pkg_spec.deps = spec.depends;

  try
    {
      lfspkg::apply_install_or_upgrade (db, pkg_spec, true);
    }
  catch (const std::exception &e)
    {
      std::printf ("%s: %s\n", _ ("upgrade error"), e.what ());
      return 1;
    }

  std::printf (_ ("Rebuilt %s %s\n"), spec.name.c_str (),
               spec.version.c_str ());
  return 0;
}

/* Sort packages so dependencies come first. */
static std::vector<std::string>
topo_sort (lfspkg::PackageDB &db, const std::vector<std::string> &pkgs)
{
  std::set<std::string> pkg_set (pkgs.begin (), pkgs.end ());
  std::vector<std::string> sorted;
  std::set<std::string> visited;

  for (const auto &p : pkgs)
    {
      /* Walk dep chain of p, emitting deps before p. */
      std::vector<std::string> stack;
      std::set<std::string> in_stack;

      auto push = [&] (auto &&self, const std::string &cur) -> bool
        {
          if (visited.count (cur))
            return true;
          if (in_stack.count (cur))
            {
              std::printf (_ ("warning: cycle detected, skipping %s\n"),
                           cur.c_str ());
              return true; /* cycle — skip to avoid infinite loop */
            }
          if (!pkg_set.count (cur))
            {
              visited.insert (cur);
              return true;
            }
          in_stack.insert (cur);

          try
            {
              auto meta = db.read_meta (cur);
              for (const auto &dep : meta.deps)
                {
                  if (!self (self, dep))
                    return false;
                }
            }
          catch (...)
            {
            }

          in_stack.erase (cur);
          visited.insert (cur);
          sorted.push_back (cur);
          return true;
        };
      push (push, p);
    }

  return sorted;
}

/* Read repo index, return name→version map. */
static std::map<std::string, std::string>
load_index_versions (const Config &cfg)
{
  std::map<std::string, std::string> vers;
  std::ifstream in (cfg.repo_dir + "/meta/index");
  if (!in)
    return vers;
  std::string line;
  while (std::getline (in, line))
    {
      if (line.empty () || line[0] == '#')
        continue;
      std::istringstream ss (line);
      std::vector<std::string> fields;
      std::string f;
      while (std::getline (ss, f, '\t'))
        fields.push_back (f);
      if (fields.size () >= 3)
        vers[fields[1]] = fields[2];
    }
  return vers;
}

/* Rebuild a set of packages, cascading to newly-stale packages.
   The 'rebuilt' set prevents re-rebuilding the same package within
   one cascade chain (guards against cyclic built_deps oscillation). */
static int
rebuild_cascade (const Config &cfg, lfspkg::PackageDB &db,
                 const std::vector<std::string> &initial,
                 std::set<std::string> &rebuilt)
{
  if (initial.empty ())
    {
      std::printf (_ ("Nothing to rebuild.\n"));
      return 0;
    }

  /* Filter out packages already rebuilt in this cascade. */
  std::vector<std::string> to_build;
  for (const auto &pkg : initial)
    {
      if (rebuilt.count (pkg))
        continue;
      to_build.push_back (pkg);
    }

  if (to_build.empty ())
    return 0;

  std::vector<std::string> ordered = topo_sort (db, to_build);

  for (const auto &pkg : ordered)
    {
      int rc = rebuild_package (cfg, db, pkg);
      if (rc != 0)
        return rc;
      rebuilt.insert (pkg);
    }

  /* Check for newly-stale packages (cascade). */
  auto new_stale = lfspkg::find_stale_packages (db);
  if (!new_stale.empty ())
    {
      std::printf (_ ("%d package(s) now stale, rebuilding...\n"),
                   static_cast<int> (new_stale.size ()));
      return rebuild_cascade (cfg, db, new_stale, rebuilt);
    }

  return 0;
}

/* ------------------------------------------------------------------ */

int
cmd_install (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp install <packages...>\n"));
      return 1;
    }

  Config cfg = load_config ();
  auto db = make_db (cfg);

  /* Ensure repo is available. */
  struct stat st;
  if (stat (cfg.repo_dir.c_str (), &st) != 0)
    cmd_update (0, nullptr);

  std::set<std::string> installing;
  int rc = 0;
  for (int i = 1; i < argc; ++i)
    {
      rc = install_package (cfg, db, argv[i], installing);
      if (rc != 0)
        break;
    }

  /* Cascade: rebuild anything made stale by this install. */
  if (rc == 0)
    {
      auto stale = lfspkg::find_stale_packages (db);
      if (!stale.empty ())
        {
          std::printf (_ ("%d package(s) stale, rebuilding...\n"),
                       static_cast<int> (stale.size ()));
          std::set<std::string> rebuilt;
          rc = rebuild_cascade (cfg, db, stale, rebuilt);
        }
    }

  return rc;
}

int
cmd_rebuild (int argc, char **argv)
{
  Config cfg = load_config ();
  auto db = make_db (cfg);

  /* Ensure repo is available. */
  struct stat st;
  if (stat (cfg.repo_dir.c_str (), &st) != 0)
    cmd_update (0, nullptr);

  std::set<std::string> rebuilt;

  if (argc < 2 || std::strcmp (argv[1], "--stale") == 0)
    {
      auto stale = lfspkg::find_stale_packages (db);
      if (stale.empty ())
        {
          std::printf (_ ("No stale packages found.\n"));
          return 0;
        }
      std::printf (_ ("Rebuilding %d stale package(s)...\n"),
                   static_cast<int> (stale.size ()));
      return rebuild_cascade (cfg, db, stale, rebuilt);
    }

  if (std::strcmp (argv[1], "--all") == 0)
    {
      auto all = db.list_packages ();
      if (all.empty ())
        {
          std::printf (_ ("No packages installed.\n"));
          return 0;
        }
      std::printf (_ ("Rebuilding all %d package(s)...\n"),
                   static_cast<int> (all.size ()));
      return rebuild_cascade (cfg, db, all, rebuilt);
    }

  /* Rebuild specific packages. */
  int rc = 0;
  for (int i = 1; i < argc; ++i)
    {
      rc = rebuild_package (cfg, db, argv[i]);
      if (rc != 0)
        break;
      rebuilt.insert (argv[i]);
    }

  /* Cascade after explicit rebuilds. */
  if (rc == 0)
    {
      auto stale = lfspkg::find_stale_packages (db);
      if (!stale.empty ())
        {
          std::printf (_ ("%d package(s) now stale, rebuilding...\n"),
                       static_cast<int> (stale.size ()));
          rc = rebuild_cascade (cfg, db, stale, rebuilt);
        }
    }

  return rc;
}

int
cmd_upgrade (int argc, char **argv)
{
  Config cfg = load_config ();
  auto db = make_db (cfg);

  /* Ensure repo is available. */
  struct stat st;
  if (stat (cfg.repo_dir.c_str (), &st) != 0)
    cmd_update (0, nullptr);

  auto index_vers = load_index_versions (cfg);
  if (index_vers.empty ())
    {
      std::printf (_ ("No package index. Run 'qp update' first.\n"));
      return 1;
    }

  std::vector<std::string> to_upgrade;

  if (argc < 2)
    {
      /* No args: find all packages with newer versions. */
      for (const auto &pkg : db.list_packages ())
        {
          auto it = index_vers.find (pkg);
          if (it == index_vers.end ())
            continue;
          std::string installed;
          try
            {
              installed = db.read_meta (pkg).version;
            }
          catch (...)
            {
              continue;
            }
          if (installed != it->second)
            {
              std::printf (_ ("%s: %s -> %s\n"), pkg.c_str (),
                           installed.c_str (), it->second.c_str ());
              to_upgrade.push_back (pkg);
            }
        }
    }
  else
    {
      /* Specific packages. */
      for (int i = 1; i < argc; ++i)
        {
          const char *pkg = argv[i];
          if (!db.installed (pkg))
            {
              std::printf (_ ("%s: not installed.\n"), pkg);
              return 1;
            }
          auto it = index_vers.find (pkg);
          if (it == index_vers.end ())
            {
              std::printf (_ ("%s: not found in repository.\n"), pkg);
              return 1;
            }
          std::string installed = db.read_meta (pkg).version;
          if (installed == it->second)
            {
              std::printf (_ ("%s: already up to date (%s).\n"), pkg,
                           installed.c_str ());
              continue;
            }
          std::printf (_ ("%s: %s -> %s\n"), pkg, installed.c_str (),
                       it->second.c_str ());
          to_upgrade.push_back (pkg);
        }
    }

  if (to_upgrade.empty ())
    {
      std::printf (_ ("All packages up to date.\n"));
      return 0;
    }

  std::printf (_ ("Upgrading %d package(s)...\n"),
               static_cast<int> (to_upgrade.size ()));
  std::set<std::string> rebuilt;
  return rebuild_cascade (cfg, db, to_upgrade, rebuilt);
}

int
cmd_list (int, char **)
{
  auto db = make_db (load_config ());

  auto pkgs = db.list_packages ();
  if (pkgs.empty ())
    {
      std::printf (_ ("No packages installed.\n"));
      return 0;
    }

  for (const auto &pkg : pkgs)
    {
      try
        {
          auto meta = db.read_meta (pkg);
          std::printf ("%-20s %s\n", meta.name.c_str (),
                       meta.version.c_str ());
        }
      catch (...)
        {
          std::printf ("%-20s (error reading meta)\n", pkg.c_str ());
        }
    }

  return 0;
}

int
cmd_remove (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp remove <packages...>\n"));
      return 1;
    }

  Config cfg = load_config ();
  auto db = make_db (cfg);
  auto owners = db.load_owners ();
  fs::path targetRoot = lfspkg::default_target_root ();

  int rc = 0;
  for (int i = 1; i < argc; ++i)
    {
      const char *pkg = argv[i];
      if (!db.installed (pkg))
        {
          std::printf (_ ("%s: not installed.\n"), pkg);
          rc = 1;
          continue;
        }

      auto revdeps = lfspkg::reverse_dependencies (db, pkg);
      if (!revdeps.empty ())
        {
          std::printf (_ ("%s: required by:"), pkg);
          for (const auto &d : revdeps)
            std::printf (" %s", d.c_str ());
          std::printf ("\n");
          std::printf (_ ("Use 'qp remove' again to force-remove anyway.\n"));
          rc = 1;
          continue;
        }

      lfspkg::remove_package_files (db, pkg, targetRoot, owners);
      std::printf (_ ("Removed %s\n"), pkg);
    }

  db.save_owners_atomic (owners);
  return rc;
}

int
cmd_register (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp register <pkg> [version] [deps...]\n"));
      return 1;
    }

  Config cfg = load_config ();
  auto db = make_db (cfg);

  const char *name = argv[1];
  const char *version = argc >= 3 ? argv[2] : "0";

  if (db.installed (name))
    {
      std::printf (_ ("%s: already registered.\n"), name);
      return 1;
    }

  std::vector<std::string> deps;
  for (int i = 3; i < argc; ++i)
    deps.push_back (argv[i]);

  lfspkg::PackageMeta meta;
  meta.name = name;
  meta.version = version;
  meta.install_time = std::to_string (std::time (nullptr));
  meta.stage_dir = "";
  meta.deps = deps;

  db.ensure ();
  db.write_meta_atomic (meta);
  db.write_manifest_atomic (name, {});
  std::printf (_ ("Registered %s %s\n"), name, version);
  return 0;
}

int
cmd_unregister (int argc, char **argv)
{
  if (argc < 2)
    {
      std::printf (_ ("Usage: qp unregister <packages...>\n"));
      return 1;
    }

  Config cfg = load_config ();
  auto db = make_db (cfg);

  int rc = 0;
  for (int i = 1; i < argc; ++i)
    {
      const char *pkg = argv[i];
      if (!db.installed (pkg))
        {
          std::printf (_ ("%s: not registered.\n"), pkg);
          rc = 1;
          continue;
        }

      /* Remove owned paths from owners. */
      auto owners = db.load_owners ();
      try
        {
          auto manifest = db.read_manifest (pkg);
          bool changed = false;
          for (const auto &e : manifest)
            {
              if (e.type != 'D' && owners.count (e.installPath)
                  && owners[e.installPath] == pkg)
                {
                  owners.erase (e.installPath);
                  changed = true;
                }
            }
          if (changed)
            db.save_owners_atomic (owners);
        }
      catch (...)
        {
        }

      std::error_code ec1, ec2;
      fs::remove (db.meta_path (pkg), ec1);
      fs::remove (db.manifest_path (pkg), ec2);
      std::printf (_ ("Unregistered %s\n"), pkg);
    }

  return rc;
}

const Subcommand *
find_subcommand (const char *name)
{
  for (const Subcommand *sc = subcommands; sc->name != nullptr; ++sc)
    {
      if (std::strcmp (sc->name, name) == 0)
        return sc;
    }
  return nullptr;
}
